name: primeirapipeline
on:
  push: 
    branches: ["master"]
  workflow_dispatch: 
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "primeira acao"
        run: echo "Hello World"
      - name: "segunda acao"
        run: |
          echo "Criado um workflow" 
          echo "Show de bola" 
      - name: "Script Python"
        run: |
          variavel = "Hello World !!! " 
          print(variavel)
        shell: python
  segundo-job:
    name: "Instalacao Ambiente NodeJs"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificacao version Nodejs" 
        run: node --version
      - name: "Definicao da versao 20.13.1 no NodeJs"
      - uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'
      - name: "Verificacao version Nodejs depois de instalar" 
        run: node --version
