name: primeirapipeline
on:
  push: 
    branches: ["master"]
  workflow_dispatch: 
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "primeira acao"
        run: echo "Hello World"
      - name: "segunda acao"
        run: |
          echo "Criado um workflow" 
          echo "Show de bola" 
          
